services:
  - type: web
    name: kareys-bot
    runtime: python
    env: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
